# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Static inventory of runnable environment-shaped repository configs.

The migration script and the public catalog intentionally share this scanner so
legacy units cannot disappear merely because the two surfaces use different
discovery rules.  Discovery reads YAML only; it imports no environment code and
starts no services.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping

import yaml


MIGRATION_INVENTORY_PATH = Path("migration/environment-manifest-inventory.json")
MIGRATION_DRAFT_HEADER = "# Generated by scripts/migrate_environment_manifests.py."
MIGRATION_TODO_PREFIX = "TODO_REQUIRED"


@dataclass(frozen=True)
class RunnableUnit:
    """One config-shaped migration candidate discovered without importing code."""

    name: str
    kind: str
    config_path: Path
    manifest_path: Path
    registry: str
    blocker: str | None = None
    lexical_config_path: Path | None = None


def _yaml_mapping(path: Path) -> dict[str, Any] | None:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return None
    return _yaml_mapping_content(content)


def _yaml_mapping_content(content: str) -> dict[str, Any] | None:
    try:
        value = yaml.safe_load(content)
    except yaml.YAMLError:
        return None
    return value if isinstance(value, dict) else None


def _contains_key(value: object, key: str) -> bool:
    if isinstance(value, Mapping):
        return key in value or any(_contains_key(item, key) for item in value.values())
    if isinstance(value, list):
        return any(_contains_key(item, key) for item in value)
    return False


def _declares_benchmark_dataset(value: object) -> bool:
    if isinstance(value, Mapping):
        return value.get("type") == "benchmark" or any(_declares_benchmark_dataset(item) for item in value.values())
    if isinstance(value, list):
        return any(_declares_benchmark_dataset(item) for item in value)
    return False


def _declares_runnable_resources_config(value: object) -> bool:
    """Return whether a component config carries verifier, agent, and tasks."""

    return (
        _contains_key(value, "resources_servers")
        and _contains_key(value, "responses_api_agents")
        and _contains_key(value, "datasets")
    )


def is_runnable_unit_config_content(registry: str, content: str) -> bool:
    """Apply discovery's runnable-unit test to immutable config content."""

    if registry in {"environments", "example_environments"}:
        return True
    raw = _yaml_mapping_content(content)
    if registry == "benchmarks":
        return raw is None or _declares_benchmark_dataset(raw)
    if registry == "resources_servers":
        return raw is not None and _declares_runnable_resources_config(raw)
    return False


def _environment_units(repo_root: Path, registry: str) -> list[RunnableUnit]:
    base = repo_root / registry
    if not base.is_dir():
        return []
    units: list[RunnableUnit] = []
    for path in sorted(base.rglob("config.yaml")):
        parent = path.parent
        units.append(
            RunnableUnit(
                name=parent.relative_to(base).as_posix(),
                kind="environment",
                config_path=path.resolve(),
                manifest_path=(parent / "manifest.yaml").resolve(),
                registry=registry,
                lexical_config_path=path.absolute(),
            )
        )
    return units


def _benchmark_units(repo_root: Path) -> list[RunnableUnit]:
    base = repo_root / "benchmarks"
    if not base.is_dir():
        return []
    units: list[RunnableUnit] = []
    for path in sorted((*base.rglob("*.yaml"), *base.rglob("*.yml"))):
        # A migration draft mirrors benchmark datasets by design, but it is
        # metadata rather than another runnable benchmark config.
        if path.name == "manifest.yaml":
            continue
        raw = _yaml_mapping(path)
        # Preserve existing benchmark discovery behavior for malformed YAML:
        # keep it visible so migration/CI records the error instead of hiding it.
        if raw is not None and not _declares_benchmark_dataset(raw):
            continue
        relative = path.relative_to(base)
        canonical = path.name == "config.yaml"
        name = relative.parent.as_posix() if canonical else relative.with_suffix("").as_posix()
        blocker = None
        if not canonical:
            blocker = (
                "noncanonical benchmark config placement cannot be represented by one adjacent manifest "
                "without changing its registry identity"
            )
        units.append(
            RunnableUnit(
                name=name,
                kind="benchmark",
                config_path=path.resolve(),
                manifest_path=(path.parent / "manifest.yaml").resolve(),
                registry="benchmarks",
                blocker=blocker,
                lexical_config_path=path.absolute(),
            )
        )
    return units


def discover_resources_server_units(repo_root: Path) -> tuple[RunnableUnit, ...]:
    """Find component configs that independently compose a runnable workload."""

    base = repo_root.resolve() / "resources_servers"
    if not base.is_dir():
        return ()
    units: list[RunnableUnit] = []
    for component_dir in sorted(path for path in base.iterdir() if path.is_dir()):
        config_dir = component_dir / "configs"
        candidates: list[Path] = []
        if config_dir.is_dir():
            for path in sorted((*config_dir.glob("*.yaml"), *config_dir.glob("*.yml"))):
                raw = _yaml_mapping(path)
                if raw is not None and _declares_runnable_resources_config(raw):
                    candidates.append(path)
        if not candidates:
            continue
        blocker = None
        if len(candidates) > 1:
            blocker = (
                f"{len(candidates)} runnable configs share one resources-server registry identity; "
                "select or split them before adding a manifest"
            )
        for path in candidates:
            units.append(
                RunnableUnit(
                    name=component_dir.name,
                    kind="environment",
                    config_path=path.resolve(),
                    manifest_path=(component_dir / "manifest.yaml").resolve(),
                    registry="resources_servers",
                    blocker=blocker,
                    lexical_config_path=path.absolute(),
                )
            )
    return tuple(units)


def discover_runnable_units(repo_root: Path) -> tuple[RunnableUnit, ...]:
    """Inventory known registry placements without changing runtime discovery."""

    root = repo_root.resolve()
    candidates = [
        *_environment_units(root, "environments"),
        *_environment_units(root, "example_environments"),
        *_benchmark_units(root),
        *discover_resources_server_units(root),
    ]
    unique: dict[tuple[str, str, Path], RunnableUnit] = {}
    for unit in candidates:
        unique[(unit.kind, unit.name, unit.config_path)] = unit
    return tuple(
        sorted(
            unique.values(),
            key=lambda unit: (unit.kind, unit.name.casefold(), unit.registry, unit.config_path.as_posix()),
        )
    )


def _contains_migration_todo(value: object) -> bool:
    if isinstance(value, Mapping):
        return any(_contains_migration_todo(item) for item in value.values())
    if isinstance(value, list):
        return any(_contains_migration_todo(item) for item in value)
    return isinstance(value, str) and value.startswith(MIGRATION_TODO_PREFIX)


def is_generated_migration_draft_content(content: str) -> bool:
    """Recognize an invalid script-owned migration draft from immutable content."""

    try:
        payload = yaml.safe_load(content)
    except yaml.YAMLError:
        return False
    if not content.startswith(MIGRATION_DRAFT_HEADER) or not _contains_migration_todo(payload):
        return False

    # A schema-valid manifest is complete even if an authored free-text value
    # happens to begin with the marker.
    from nemo_gym.environment_manifest import ManifestError, dump_manifest

    try:
        dump_manifest(payload)
    except ManifestError:
        return True
    return False


def is_generated_migration_draft(path: Path) -> bool:
    """Recognize a parseable script-owned draft with an unresolved TODO value."""

    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return False
    return is_generated_migration_draft_content(content)


def _draft_paths_from_inventory_payload(
    repo_root: Path,
    payload: object,
    *,
    require_current_draft: bool,
) -> frozenset[Path]:
    root = Path(os.path.abspath(repo_root))
    units = payload.get("units") if isinstance(payload, Mapping) else None
    if not isinstance(units, list):
        return frozenset()
    drafts: set[Path] = set()
    for record in units:
        if not isinstance(record, Mapping) or record.get("status") != "drafted":
            continue
        relative = record.get("manifest_path")
        if not isinstance(relative, str) or not relative:
            continue
        candidate = Path(os.path.abspath(root / relative))
        try:
            relative_candidate = candidate.relative_to(root)
            cursor = root
            for part in relative_candidate.parts:
                cursor /= part
                if cursor.is_symlink():
                    raise ValueError(f"symbolic-link migration draft: {cursor}")
        except (OSError, ValueError):
            continue
        if not require_current_draft or is_generated_migration_draft(candidate):
            drafts.add(candidate)
    return frozenset(drafts)


def migration_draft_paths_from_inventory_content(repo_root: Path, content: str) -> frozenset[Path]:
    """Read draft paths from a base-revision inventory without consulting worktree files."""

    try:
        payload = json.loads(content)
    except json.JSONDecodeError:
        return frozenset()
    return _draft_paths_from_inventory_payload(repo_root, payload, require_current_draft=False)


def is_tracked_migration_draft(path: Path, repo_roots: Iterable[Path]) -> bool:
    """Return whether one current generated draft is listed in an inventory."""

    candidate = Path(os.path.abspath(path))
    for raw_root in repo_roots:
        root = Path(os.path.abspath(raw_root))
        try:
            candidate.relative_to(root)
        except ValueError:
            continue
        if candidate in tracked_migration_draft_paths(root):
            return True
    return False


def tracked_migration_draft_paths(
    repo_root: Path,
    *,
    inventory_path: Path = MIGRATION_INVENTORY_PATH,
) -> frozenset[Path]:
    """Return generated TODO manifests explicitly tracked by the migration wave."""

    root = Path(os.path.abspath(repo_root))
    inventory_path = inventory_path if inventory_path.is_absolute() else root / inventory_path
    try:
        payload = json.loads(inventory_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return frozenset()
    return _draft_paths_from_inventory_payload(root, payload, require_current_draft=True)


__all__ = [
    "MIGRATION_INVENTORY_PATH",
    "RunnableUnit",
    "discover_resources_server_units",
    "discover_runnable_units",
    "is_generated_migration_draft",
    "is_generated_migration_draft_content",
    "is_runnable_unit_config_content",
    "is_tracked_migration_draft",
    "migration_draft_paths_from_inventory_content",
    "tracked_migration_draft_paths",
]
