# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Unit + golden-parity tests for the ported EOG verifier engine.

The golden file (fixtures/verifier_parity_golden.json) is generated by running the SAME
input cases through the ORIGINAL EnterpriseOps-Gym engine (see generate_parity_golden.py,
run inside the EOG checkout's venv). These tests pin our port to upstream byte-for-byte.
"""

import asyncio
import json
from pathlib import Path

import pytest

from resources_servers.enterpriseops_gym.verifier_engine import (
    VerifierEngine,
    compare_values,
    extract_json_from_judge_response,
    extract_llm_content,
    extract_value_from_sql_result,
)


FIXTURES_DIR = Path(__file__).parent / "fixtures"
CASES_PATH = FIXTURES_DIR / "verifier_parity_cases.json"
GOLDEN_PATH = FIXTURES_DIR / "verifier_parity_golden.json"


@pytest.mark.skipif(
    not GOLDEN_PATH.exists(),
    reason="verifier_parity_golden.json missing — generate it with generate_parity_golden.py in the EOG venv",
)
class TestGoldenParity:
    """Assert our port matches the original EOG engine's outputs on shared fixture cases."""

    def test_extraction_matches_upstream(self) -> None:
        cases = json.loads(CASES_PATH.read_text())
        golden = json.loads(GOLDEN_PATH.read_text())
        assert len(golden["extraction"]) == len(cases["extraction"])
        for case, expected in zip(cases["extraction"], golden["extraction"]):
            assert extract_value_from_sql_result(case) == expected, f"extraction mismatch for case: {case}"

    def test_comparison_matches_upstream(self) -> None:
        cases = json.loads(CASES_PATH.read_text())
        golden = json.loads(GOLDEN_PATH.read_text())
        assert len(golden["comparison"]) == len(cases["comparison"])
        for case, expected in zip(cases["comparison"], golden["comparison"]):
            actual = compare_values(case["actual"], case["expected"], case["comparison_type"])
            assert actual == expected, f"comparison mismatch for case: {case}"


class TestExtractionSemantics:
    """Direct pins of the quirkier upstream extraction rules."""

    def test_single_row_single_column_unwraps_scalar(self) -> None:
        assert extract_value_from_sql_result({"success": True, "result": {"data": [{"c": "h24x7"}]}}) == "h24x7"

    def test_single_row_multi_column_returns_row_dict(self) -> None:
        assert extract_value_from_sql_result({"success": True, "result": {"data": [{"a": 1, "b": 2}]}}) == {
            "a": 1,
            "b": 2,
        }

    def test_failure_with_mcp_content_returns_text(self) -> None:
        result = {"success": False, "result": {"content": [{"type": "text", "text": "boom"}]}}
        assert extract_value_from_sql_result(result) == "boom"

    def test_failure_without_content_returns_none(self) -> None:
        assert extract_value_from_sql_result({"success": False}) is None


class TestComparisonSemantics:
    def test_equals_is_type_strict(self) -> None:
        # Upstream uses plain ==, so 0 != "0". SQL ints vs JSON strings matter for parity.
        assert compare_values(0, "0", "equals")["passed"] is False
        assert compare_values(0, 0, "equals")["passed"] is True

    def test_incomparable_types_fail_gracefully(self) -> None:
        result = compare_values("5", 3, "greater_than")
        assert result["passed"] is False
        assert result["details"].startswith("Comparison error")

    def test_unknown_comparison_type(self) -> None:
        result = compare_values(1, 1, "approximately")
        assert result["passed"] is False
        assert "Unknown comparison type" in result["details"]


class TestJudgeParsing:
    def test_fenced_json_block(self) -> None:
        text = 'Sure!\n```json\n{"score": 9, "reasoning": "good"}\n```'
        assert json.loads(extract_json_from_judge_response(text)) == {"score": 9, "reasoning": "good"}

    def test_bare_fence(self) -> None:
        text = '```\n{"score": 3, "reasoning": "bad"}\n```'
        assert json.loads(extract_json_from_judge_response(text)) == {"score": 3, "reasoning": "bad"}

    def test_extract_llm_content_priority(self) -> None:
        assert extract_llm_content({"content": "a", "text": "b"}) == "a"
        assert extract_llm_content({"text": "b"}) == "b"
        assert extract_llm_content({"response": "c"}) == "c"


class _FakeSQLClient:
    """Minimal stand-in for MCPGymClient's run_sql in judge tests."""

    def __init__(self, result):
        self._result = result

    async def run_sql(self, query, database_id, context=None):
        return self._result


class TestResponseCheckJudge:
    def _engine(self, judge_text: str) -> VerifierEngine:
        async def judge_fn(system_prompt: str, user_prompt: str) -> str:
            return judge_text

        client = _FakeSQLClient({"success": True, "result": {"data": [{"case_id": 1233}]}})
        return VerifierEngine(gym_clients={"g": client}, judge_fn=judge_fn)

    def _verifier(self) -> dict:
        return {
            "verifier_type": "response_check",
            "name": "answer_check",
            "gym_name": "g",
            "validation_config": {
                "sql_query": "SELECT case_id FROM cases;",
                "comparison_prompt": "Does the response mention the case id?",
                "minimum_comparison_value": 7,
            },
        }

    def test_judge_pass(self) -> None:
        engine = self._engine('```json\n{"score": 9, "reasoning": "mentions 1233"}\n```')
        result = asyncio.run(
            engine.execute_verifier(self._verifier(), {"content": "Case 1233 filed."}, "db1", None, gym_name="g")
        )
        assert result["passed"] is True
        assert result["score"] == 9

    def test_judge_fail_below_minimum(self) -> None:
        engine = self._engine('{"score": 4, "reasoning": "vague"}')
        result = asyncio.run(
            engine.execute_verifier(self._verifier(), {"content": "Done."}, "db1", None, gym_name="g")
        )
        assert result["passed"] is False

    def test_no_judge_configured_fails_cleanly(self) -> None:
        client = _FakeSQLClient({"success": True, "result": {"data": []}})
        engine = VerifierEngine(gym_clients={"g": client}, judge_fn=None)
        result = asyncio.run(engine.execute_verifier(self._verifier(), {"content": "x"}, "db1", None, gym_name="g"))
        assert result["passed"] is False
        assert "Judge comparison failed" in result["error"]

    def test_unsupported_verifier_type(self) -> None:
        engine = VerifierEngine(gym_clients={"g": _FakeSQLClient({})}, judge_fn=None)
        result = asyncio.run(engine.execute_verifier({"verifier_type": "nope"}, {}, "db1"))
        assert result == {"passed": False, "error": "Unsupported verifier type: nope"}


class TestRunVerifiersCollapse:
    def test_collapse_and_skip_semantics(self) -> None:
        client = _FakeSQLClient({"success": True, "result": {"data": [{"c": 1}]}})
        engine = VerifierEngine(gym_clients={"g": client}, judge_fn=None)

        verifiers = [
            # Fails (1 != 2), then a same-named pass overwrites it.
            {
                "verifier_type": "database_state",
                "name": "dup",
                "gym_name": "g",
                "validation_config": {"query": "q", "expected_value": 2},
            },
            {
                "verifier_type": "database_state",
                "name": "dup",
                "gym_name": "g",
                "validation_config": {"query": "q", "expected_value": 1},
            },
            # Unknown gym -> skipped entirely.
            {
                "verifier_type": "database_state",
                "name": "orphan",
                "gym_name": "missing",
                "validation_config": {"query": "q", "expected_value": 1},
            },
        ]
        collapsed, all_results = asyncio.run(
            engine.run_verifiers(verifiers, {"content": ""}, {"g": "db1"}, {"g": None})
        )

        assert list(collapsed.keys()) == ["dup"]
        assert collapsed["dup"]["passed"] is True  # last-per-name wins
        assert len(all_results) == 3
        assert [r["skipped"] for r in all_results] == [False, False, True]
        assert [r["result"]["passed"] for r in all_results] == [False, True, False]
