config_paths:
- resources_servers/over_refusal_detection/configs/over_refusal_detection.yaml
over_refusal_detection_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: over_refusal_detection
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/over_refusal_detection/data/train.jsonl
      - name: example
        type: example
        jsonl_fpath: resources_servers/over_refusal_detection/data/example.jsonl
