/**
 * Scorers data — the source of truth for the Scorers Library.
 *
 * Each entry describes a `verify()` pattern shipped under `resources_servers/`.
 * Adding a scorer here is part of shipping a new resources server; the data
 * here drives the catalog page at /build-environments/verification/scorers.
 *
 * Schema is enforced by the TypeScript type below. Source citations point at
 * actual `verify()` lines so the next Content Audit can re-verify each entry.
 */

export type ScorerPattern =
  | "exact-match"
  | "llm-judge"
  | "code-execution"
  | "structural"
  | "stateful"
  | "custom-domain";

export interface Scorer {
  id: string;
  /** Display name (the env directory name). */
  name: string;
  /** Which pattern this scorer follows. Filterable. */
  pattern: ScorerPattern;
  /** Domain tags (math, coding, agent, knowledge, instruction_following, etc.). Filterable. */
  domain: string[];
  /** True when verify() calls a separate model server. */
  judge_required: boolean;
  /** True when verify() is fully deterministic given the same input. */
  deterministic: boolean;
  /** Source path to the env's app.py. */
  source_path: string;
  /** Line number of `async def verify()` in source_path. */
  verify_line: number;
  /** One-line description of what this scorer scores. */
  description: string;
  /** When to copy this scorer as a starting point. */
  use_when: string;
  /** Load-bearing config knobs from the Pydantic config class. */
  config_knobs: string[];
}

const REPO_BASE = "https://github.com/NVIDIA-NeMo/Gym/blob/main";

export function sourceUrl(scorer: Scorer): string {
  return `${REPO_BASE}/${scorer.source_path}#L${scorer.verify_line}`;
}

export const SCORERS: Scorer[] = [
  // --- exact-match / boxed-answer extraction ---
  {
    id: "mcqa",
    name: "mcqa",
    pattern: "exact-match",
    domain: ["knowledge"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/mcqa/app.py",
    verify_line: 253,
    description: "Multiple-choice letter extraction.",
    use_when: "Tasks with a single correct letter answer; verifier extracts via grading_mode rule.",
    config_knobs: ["grading_mode"],
  },
  {
    id: "gpqa_diamond",
    name: "gpqa_diamond",
    pattern: "exact-match",
    domain: ["knowledge"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/gpqa_diamond/app.py",
    verify_line: 50,
    description: "Graduate-level science MCQA via per-task regex extraction.",
    use_when: "Subclassing MCQA when each task carries its own output regex in template_metadata.",
    config_knobs: ["template_metadata.output_regex"],
  },
  {
    id: "math_with_code",
    name: "math_with_code",
    pattern: "exact-match",
    domain: ["math", "coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/math_with_code/app.py",
    verify_line: 215,
    description: "Boxed-answer extraction across assistant text and tool stdout.",
    use_when: "Math problems where the model can use code execution as a scratchpad.",
    config_knobs: [],
  },
  {
    id: "math_advanced_calculations",
    name: "math_advanced_calculations",
    pattern: "exact-match",
    domain: ["math"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/math_advanced_calculations/app.py",
    verify_line: 107,
    description: "math-verify library equivalence for advanced calculations.",
    use_when: "Math tasks where structural equivalence matters more than string match.",
    config_knobs: [],
  },
  {
    id: "math_with_judge_library",
    name: "math_with_judge (library mode)",
    pattern: "exact-match",
    domain: ["math"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/math_with_judge/app.py",
    verify_line: 121,
    description: "math-verify library equivalence with should_use_judge=False.",
    use_when: "Math tasks where library equivalence is sufficient; avoid the judge cost.",
    config_knobs: ["should_use_judge"],
  },
  {
    id: "equivalence_rule",
    name: "equivalence_rule",
    pattern: "exact-match",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/equivalence_rule/app.py",
    verify_line: 74,
    description: "Rule-based equivalence (no LLM).",
    use_when: "Custom equivalence logic codified as a regex or a small Python rule.",
    config_knobs: [],
  },

  // --- LLM-as-judge equivalence ---
  {
    id: "equivalence_llm_judge",
    name: "equivalence_llm_judge",
    pattern: "llm-judge",
    domain: ["other"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/equivalence_llm_judge/app.py",
    verify_line: 397,
    description: "Generic configurable LLM-as-judge for open-ended outputs.",
    use_when:
      "Open-ended outputs that exact-match would reject too aggressively. Pin judge model + temperature for variance control.",
    config_knobs: [
      "judge_model_server",
      "judge_responses_create_params",
      "judge_prompt_template_fpath",
      "judge_equal_label",
      "judge_endpoint_max_concurrency",
    ],
  },
  {
    id: "math_with_judge_judge",
    name: "math_with_judge (judge mode)",
    pattern: "llm-judge",
    domain: ["math"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/math_with_judge/app.py",
    verify_line: 121,
    description: "Math-specific arena-hard prompt judge.",
    use_when:
      "Math tasks where library equivalence misses semantically-equal answers (e.g., different proof formats).",
    config_knobs: ["should_use_judge", "judge_model_server"],
  },
  {
    id: "proof_judge",
    name: "proof_judge",
    pattern: "llm-judge",
    domain: ["math"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/proof_judge/app.py",
    verify_line: 228,
    description: "Proof grading via LLM judge.",
    use_when: "Free-form proof responses that need step-level evaluation.",
    config_knobs: ["judge_model_server"],
  },
  {
    id: "swerl_llm_judge",
    name: "swerl_llm_judge",
    pattern: "llm-judge",
    domain: ["coding"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/swerl_llm_judge/app.py",
    verify_line: 176,
    description: "Domain judge for SWE-RL.",
    use_when: "SWE-bench-style outputs that need narrative-quality scoring.",
    config_knobs: ["judge_model_server"],
  },
  {
    id: "terminus_judge",
    name: "terminus_judge",
    pattern: "llm-judge",
    domain: ["agent"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/terminus_judge/app.py",
    verify_line: 269,
    description: "Domain judge for Terminus tasks.",
    use_when: "Terminus-style agent rollouts needing narrative scoring.",
    config_knobs: ["judge_model_server"],
  },
  {
    id: "genrm_compare",
    name: "genrm_compare",
    pattern: "llm-judge",
    domain: ["other"],
    judge_required: true,
    deterministic: false,
    source_path: "resources_servers/genrm_compare/app.py",
    verify_line: 197,
    description: "Pairwise comparison via generative reward model.",
    use_when: "Reward modeling: scoring response_1 vs response_2 against a principle.",
    config_knobs: ["judge_model_server"],
  },

  // --- code execution ---
  {
    id: "competitive_coding_challenges",
    name: "competitive_coding_challenges",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/competitive_coding_challenges/app.py",
    verify_line: 276,
    description: "Competitive coding eval via ccc_eval.CCCEvaluator.",
    use_when: "Competitive-programming-style tasks with full test-case suites.",
    config_knobs: ["unit_test_timeout_secs", "num_processes"],
  },
  {
    id: "code_gen",
    name: "code_gen",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/code_gen/app.py",
    verify_line: 148,
    description: "LiveCodeBench-format code generation with test execution.",
    use_when: "Code generation against a fixed test harness; supports thinking-block penalties.",
    config_knobs: ["num_processes", "unit_test_timeout_secs", "reasoning_format_penalty"],
  },
  {
    id: "bird_sql",
    name: "bird_sql",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/bird_sql/app.py",
    verify_line: 135,
    description: "SQL execution against a target DB fixture (BIRD benchmark).",
    use_when: "SQL-generation tasks with ground-truth queries and known DB state.",
    config_knobs: [],
  },
  {
    id: "text_to_sql",
    name: "text_to_sql",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/text_to_sql/app.py",
    verify_line: 224,
    description: "SQL execution against a per-task DB.",
    use_when: "Text-to-SQL tasks with arbitrary schemas.",
    config_knobs: [],
  },
  {
    id: "spider2_lite",
    name: "spider2_lite",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/spider2_lite/app.py",
    verify_line: 132,
    description: "Spider 2.0 SQL execution (lite variant).",
    use_when: "Spider 2.0 Lite benchmark.",
    config_knobs: [],
  },
  {
    id: "swerl_gen",
    name: "swerl_gen",
    pattern: "code-execution",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/swerl_gen/app.py",
    verify_line: 96,
    description: "SWE-RL: patch application + test execution.",
    use_when: "SWE-bench-style patch generation.",
    config_knobs: [],
  },

  // --- structural / schema validation ---
  {
    id: "structured_outputs",
    name: "structured_outputs",
    pattern: "structural",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/structured_outputs/app.py",
    verify_line: 197,
    description: "JSON Schema validation against expected output shape.",
    use_when: "Tasks where the model must produce JSON conforming to a strict schema.",
    config_knobs: ["response_mode"],
  },
  {
    id: "format_verification",
    name: "format_verification",
    pattern: "structural",
    domain: ["instruction_following"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/format_verification/app.py",
    verify_line: 48,
    description: "Citations, list shapes, and other freeform format checks.",
    use_when: "Output-format constraints like 'must include 3 citations' or 'numbered list of 5 items'.",
    config_knobs: [],
  },
  {
    id: "instruction_following",
    name: "instruction_following",
    pattern: "structural",
    domain: ["instruction_following"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/instruction_following/app.py",
    verify_line: 92,
    description: "IFEval-style constraint checks.",
    use_when: "Instruction-following benchmark with deterministic constraints.",
    config_knobs: [],
  },
  {
    id: "ifbench",
    name: "ifbench",
    pattern: "structural",
    domain: ["instruction_following"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/ifbench/app.py",
    verify_line: 128,
    description: "IFBench instruction-following with thread-pool semaphore.",
    use_when: "AllenAI IFBench-style multi-instruction evaluation.",
    config_knobs: [],
  },
  {
    id: "xlam_fc",
    name: "xlam_fc",
    pattern: "structural",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/xlam_fc/app.py",
    verify_line: 109,
    description: "Function-call argument matching against expected_answers.",
    use_when: "Tool-calling tasks where exact argument match across all expected calls is required.",
    config_knobs: ["expected_answers"],
  },
  {
    id: "single_step_tool_use",
    name: "single_step_tool_use_with_argument_comparison",
    pattern: "structural",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/single_step_tool_use_with_argument_comparison/app.py",
    verify_line: 65,
    description: "Single-step tool-call argument comparison.",
    use_when: "Single-turn tool-call tasks evaluated on argument structure.",
    config_knobs: [],
  },
  {
    id: "structeval",
    name: "structeval",
    pattern: "structural",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/structeval/app.py",
    verify_line: 134,
    description: "Argument and structure comparison.",
    use_when: "Structural-comparison tasks beyond JSON schema.",
    config_knobs: [],
  },

  // --- stateful / multi-step ---
  {
    id: "example_session_state_mgmt",
    name: "example_session_state_mgmt",
    pattern: "stateful",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/example_session_state_mgmt/app.py",
    verify_line: 91,
    description: "Canonical reference for session-keyed state — counter pattern.",
    use_when: "Reference example when authoring a new stateful environment from scratch.",
    config_knobs: [],
  },
  {
    id: "workplace_assistant",
    name: "workplace_assistant",
    pattern: "stateful",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/workplace_assistant/app.py",
    verify_line: 99,
    description: "State-matching after a multi-turn workplace tool dialog.",
    use_when:
      "Agent tasks that read/write across email/calendar/CRM-style tool fixtures and score on final state.",
    config_knobs: [],
  },
  {
    id: "example_multi_step",
    name: "example_multi_step",
    pattern: "stateful",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/example_multi_step/app.py",
    verify_line: 87,
    description: "Multi-step tool-calling reference example.",
    use_when: "Reference example for a multi-step agent without session-state persistence.",
    config_knobs: [],
  },
  {
    id: "calendar",
    name: "calendar",
    pattern: "stateful",
    domain: ["agent"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/calendar/app.py",
    verify_line: 49,
    description: "Calendar tool dialog with stateful scheduling.",
    use_when: "Agent tasks involving multi-step calendar manipulation.",
    config_knobs: [],
  },
  {
    id: "tavily_search",
    name: "tavily_search",
    pattern: "stateful",
    domain: ["agent", "knowledge"],
    judge_required: false,
    deterministic: false,
    source_path: "resources_servers/tavily_search/app.py",
    verify_line: 398,
    description: "Web search via Tavily with verified answer extraction.",
    use_when: "Agent tasks that require live web search before answering.",
    config_knobs: [],
  },
  {
    id: "newton_bench",
    name: "newton_bench",
    pattern: "stateful",
    domain: ["agent", "math"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/newton_bench/app.py",
    verify_line: 269,
    description: "Newton physics-reasoning benchmark with stateful tools.",
    use_when: "Multi-step physics reasoning that requires accumulating tool results.",
    config_knobs: [],
  },

  // --- custom domain ---
  {
    id: "rdkit_chemistry",
    name: "rdkit_chemistry",
    pattern: "custom-domain",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/rdkit_chemistry/app.py",
    verify_line: 334,
    description: "Molecule equivalence via RDKit.",
    use_when: "Chemistry tasks scored on molecular structure equivalence.",
    config_knobs: [],
  },
  {
    id: "aalcr",
    name: "aalcr",
    pattern: "custom-domain",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/aalcr/app.py",
    verify_line: 61,
    description: "Legal/contract reasoning eval.",
    use_when: "Legal-reasoning tasks (AALCR benchmark).",
    config_knobs: [],
  },
  {
    id: "cvdp",
    name: "cvdp",
    pattern: "custom-domain",
    domain: ["coding"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/cvdp/app.py",
    verify_line: 378,
    description: "Comprehensive Verilog Design Problems hardware verification.",
    use_when: "Hardware/HDL design tasks.",
    config_knobs: [],
  },
  {
    id: "proof_verification",
    name: "proof_verification",
    pattern: "custom-domain",
    domain: ["math"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/proof_verification/app.py",
    verify_line: 184,
    description: "Formal proof checking.",
    use_when: "Formal-proof tasks with checkable proof artifacts.",
    config_knobs: [],
  },
  {
    id: "math_formal_lean",
    name: "math_formal_lean",
    pattern: "custom-domain",
    domain: ["math"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/math_formal_lean/app.py",
    verify_line: 398,
    description: "Lean theorem prover verification.",
    use_when: "Lean 4 formal-proof tasks (compiler-in-the-loop).",
    config_knobs: [],
  },
  {
    id: "nvarc",
    name: "nvarc",
    pattern: "custom-domain",
    domain: ["other"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/nvarc/app.py",
    verify_line: 198,
    description: "NVARC benchmark.",
    use_when: "NVARC benchmark.",
    config_knobs: [],
  },
  {
    id: "abstention",
    name: "abstention",
    pattern: "custom-domain",
    domain: ["safety"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/abstention/app.py",
    verify_line: 302,
    description: "Abstention scoring (model declines to answer).",
    use_when: "Safety-eval tasks scoring willingness-to-abstain on unanswerable prompts.",
    config_knobs: [],
  },
  {
    id: "jailbreak_detection",
    name: "jailbreak_detection",
    pattern: "custom-domain",
    domain: ["safety"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/jailbreak_detection/app.py",
    verify_line: 266,
    description: "Jailbreak-detection scoring.",
    use_when: "Adversarial / jailbreak-robustness evals.",
    config_knobs: [],
  },
  {
    id: "over_refusal_detection",
    name: "over_refusal_detection",
    pattern: "custom-domain",
    domain: ["safety"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/over_refusal_detection/app.py",
    verify_line: 206,
    description: "Over-refusal scoring (model declines benign prompts).",
    use_when: "Safety evals balancing helpfulness vs over-refusal.",
    config_knobs: [],
  },
  {
    id: "xstest",
    name: "xstest",
    pattern: "custom-domain",
    domain: ["safety"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/xstest/app.py",
    verify_line: 192,
    description: "XSTest safety / over-refusal benchmark.",
    use_when: "XSTest benchmark.",
    config_knobs: [],
  },
  {
    id: "ether0",
    name: "ether0",
    pattern: "custom-domain",
    domain: ["safety"],
    judge_required: false,
    deterministic: true,
    source_path: "resources_servers/ether0/app.py",
    verify_line: 57,
    description: "Ether0 chemistry / safety eval.",
    use_when: "Domain-specific chemistry-safety tasks.",
    config_knobs: [],
  },
];

export const PATTERN_LABELS: Record<ScorerPattern, string> = {
  "exact-match": "Exact-match",
  "llm-judge": "LLM-as-judge",
  "code-execution": "Code execution",
  structural: "Structural",
  stateful: "Stateful",
  "custom-domain": "Custom domain",
};
