# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
config_paths:
  - resources_servers/swe_external1/configs/swe_external1.yaml

swe_external1_example_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: swe_external1_golden_patch_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: example
          type: example
          jsonl_fpath: resources_servers/swe_external1/data/example.jsonl
