# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
swe_external1_resources_server:
  resources_servers:
    swe_external1:
      entrypoint: app.py
      domain: coding
      verified: false
      allowed_agents: [opencode_sandboxed_agent]
      num_workers: 1
      max_concurrency: 8
      sandbox_provider: sandbox
      sandbox_config:
        ready_timeout_s: 1200
      evaluation_timeout: 3600
      is_verifying_golden_patch: false

swe_external1_golden_patch_resources_server:
  resources_servers:
    swe_external1:
      entrypoint: app.py
      domain: coding
      verified: false
      num_workers: 1
      max_concurrency: 8
      sandbox_provider: sandbox
      sandbox_config:
        ready_timeout_s: 1200
      evaluation_timeout: 3600
      is_verifying_golden_patch: true
