config_paths:
  - resources_servers/librispeech_pc/configs/librispeech_pc.yaml

librispeech_pc_resources_server:
  _inherit_from: librispeech_pc

librispeech_pc_simple_agent:
  _inherit_from: librispeech_pc_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: librispeech_pc_resources_server
      datasets:
      - name: librispeech_pc
        type: benchmark
        jsonl_fpath: benchmarks/librispeech_pc/data/librispeech_pc_benchmark.jsonl
        prepare_script: benchmarks/librispeech_pc/prepare.py
        license: Creative Commons Attribution 4.0 International
