# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Rendering a `PairedTestReport`: markdown, its JSON twin, the terminal recap, and indexed
filenames so rerunning with different parameters doesn't overwrite a previous invocation's results.
"""

import re
from pathlib import Path
from typing import TYPE_CHECKING, List, Sequence, Tuple

import orjson

from nemo_gym.config_types import ConfigError
from nemo_gym.statistical_tests.schema import PairedTestConfig, PairedTestReport, PairedTestResult


if TYPE_CHECKING:
    from rich.table import Table


MISSING = "—"


def _fmt(value) -> str:
    if value is None:
        return MISSING
    return f"{value:.4f}" if abs(value) < 10 else f"{value:.2f}"


def _fmt_p(value) -> str:
    if value is None:
        return MISSING
    return f"{value:.4f}" if value >= 0.0001 else f"{value:.2e}"


def _fmt_bool(value) -> str:
    if value is None:
        return MISSING
    return "yes" if value else "no"


def _sanitize(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.+-]+", "-", text).strip("-")


def _framing_slug(config: PairedTestConfig) -> str:
    return "two-sided" if config.margin is None else f"margin-{config.margin:g}"


def report_stem(config: PairedTestConfig) -> str:
    """The filename (no extension) for this invocation's parameters -- see module docstring."""
    parts = [_framing_slug(config), f"alpha-{config.alpha:g}"]
    if config.metric:
        metrics_slug = "+".join(_sanitize(metric) for metric in config.metric)
        parts.insert(0, f"metric-{metrics_slug}")
    return "__".join(parts)


def _result_row(result: PairedTestResult) -> List[str]:
    return [
        f"`{result.metric}`",
        f"{result.margin:g}" if result.margin is not None else MISSING,
        str(result.n_pairs),
        _fmt(result.mean_diff),
        _fmt(result.se),
        _fmt_p(result.p_value),
        _fmt_bool(result.significant),
        _fmt(result.minimum_detectable_effect),
    ]


RESULT_HEADER = ["Metric", "Margin", "N", "Mean Δ (cand − base)", "SE", "p-value", "Significant", "MDE (80% power)"]


def _table(header: Sequence[str], alignments: Sequence[str], rows: Sequence[Sequence[str]]) -> List[str]:
    return [
        "| " + " | ".join(header) + " |",
        "|" + "|".join(alignments) + "|",
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


FRAMING_FOOTNOTE = (
    "Margin unset: two-sided test of H0 `mu_d = 0` -- `Significant = yes` means the two runs differ. "
    "Margin set: one-sided non-inferiority test of H0 `mu_d <= -margin` -- `Significant = yes` means the "
    "candidate is *not* meaningfully worse than the margin allows (the opposite reading from the "
    "two-sided case). MDE is the smallest true effect this sample could detect at 80% power."
)


def render_paired_test_markdown(report: PairedTestReport) -> str:
    lines: List[str] = ["# gym eval test", ""]
    lines += [
        f"Baseline:  `{report.baseline_rollouts_jsonl_fpath}` (agent `{report.baseline_agent}`, "
        f"{report.baseline_task_count} tasks)",
        f"Candidate: `{report.candidate_rollouts_jsonl_fpath}` (agent `{report.candidate_agent}`, "
        f"{report.candidate_task_count} tasks)",
        "",
        f"Generated {report.generated_at} by nemo-gym {report.nemo_gym_version}.",
        "",
        f"Command: `{report.command}`",
        "",
        "## Results",
        "",
    ]
    if report.results:
        lines += _table(
            RESULT_HEADER,
            ["---", "---:", "---:", "---:", "---:", "---:", "---", "---:"],
            [_result_row(result) for result in report.results],
        )
        for result in report.results:
            if result.note:
                lines.append(f"- `{result.metric}`: {result.note}")
    else:
        lines.append("No metrics were tested.")
    lines += ["", FRAMING_FOOTNOTE, ""]

    if report.notes:
        lines += ["## Notes", "", *(f"- {note}" for note in report.notes), ""]
    if report.warnings:
        lines += ["## Warnings", "", *(f"- {warning}" for warning in report.warnings), ""]

    lines += [
        "---",
        f"Generated by `gym eval test` (nemo-gym {report.nemo_gym_version}). "
        f"Machine-readable output: same filename with a `.json` extension (schema_version {report.schema_version}).",
        "",
    ]
    return "\n".join(lines)


def render_paired_test_table(report: PairedTestReport) -> List["Table"]:
    """One Rich table of every metric tested, for the terminal recap."""
    from rich.markup import escape
    from rich.table import Table

    title = (
        f"Statistical tests — {report.baseline_agent}"
        if report.baseline_agent == report.candidate_agent
        else f"Statistical tests — {report.baseline_agent} vs {report.candidate_agent}"
    )
    table = Table(title=title)
    right_justified = {"Margin", "N", "Mean Δ (cand − base)", "SE", "p-value", "MDE (80% power)"}
    for header in RESULT_HEADER:
        table.add_column(header, justify="right" if header in right_justified else "left")
    for result in report.results:
        cells = _result_row(result)
        cells[0] = escape(cells[0])
        table.add_row(*cells)
    return [table]


def write_paired_test_reports(report: PairedTestReport, config: PairedTestConfig, output_dir: Path) -> List[Path]:
    """Write the requested artifacts into `output_dir`, indexed by this invocation's parameters."""
    if output_dir.exists() and not output_dir.is_dir():
        raise ConfigError(f"--output-dir '{output_dir}' exists and is not a directory.")
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        raise ConfigError(f"Cannot write to --output-dir '{output_dir}': {e}") from e

    stem = report_stem(config)
    written: List[Path] = []
    try:
        if config.report_format in ("md", "both"):
            markdown_fpath = output_dir / f"{stem}.md"
            markdown_fpath.write_text(render_paired_test_markdown(report), encoding="utf-8")
            written.append(markdown_fpath)
        if config.report_format in ("json", "both"):
            json_fpath = output_dir / f"{stem}.json"
            json_fpath.write_bytes(orjson.dumps(report.model_dump(mode="json"), option=orjson.OPT_INDENT_2))
            written.append(json_fpath)
    except OSError as e:
        raise ConfigError(f"Cannot write the report into '{output_dir}': {e}") from e
    return written


def summary_lines(report: PairedTestReport, written: Sequence[Path]) -> Tuple[str, ...]:
    """The short stdout recap printed after the files are written."""
    lines = [
        f"Baseline:  {report.baseline_aggregate_metrics_fpath}",
        f"Candidate: {report.candidate_aggregate_metrics_fpath}",
        f"Agents compared: {report.baseline_agent}"
        + ("" if report.baseline_agent == report.candidate_agent else f" vs {report.candidate_agent}"),
    ]
    for result in report.results:
        if result.p_value is not None:
            lines.append(
                f"{result.metric}: n={result.n_pairs} mean_diff={_fmt(result.mean_diff)} "
                f"p={_fmt_p(result.p_value)} significant={_fmt_bool(result.significant)}"
            )
        elif result.note:
            lines.append(f"{result.metric}: {result.note}")
    lines += [f"Wrote: {path}" for path in written]
    return tuple(lines)
