xlam_fc:
  resources_servers:
    xlam_fc:
      entrypoint: app.py
      domain: agent
      verified: false
      description: Salesforce xlam-function-calling-60k tool calling tasks
      value: Improve tool-calling capabilities
