tau2_agent:
  responses_api_agents:
    tau2:
      entrypoint: app.py
      model_server:
        type: responses_api_models
        name: policy_model
      user_model_server:
        type: responses_api_models
        name: policy_model
      debug: false
      print_step_counts: false
      datasets: []
