config_paths:
  - responses_api_agents/deep_swe_agent/configs/deep_swe_opensandbox.yaml

deep_swe:
  _inherit_from: deep_swe_agent
  responses_api_agents:
    deep_swe_agent:
      datasets:
        - name: deep_swe
          type: benchmark
          jsonl_fpath: benchmarks/deep_swe/data/deep_swe_benchmark.jsonl
          prompt_config: null
          prepare_script: benchmarks/deep_swe/prepare.py
          num_repeats: 1
