# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Task-data schema for Political Even-handedness rows."""

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TaskData(BaseModel):
    """Source columns consumed by the paired agent or retained as provenance."""

    model_config = ConfigDict(extra="allow")

    id: Optional[str] = Field(default=None, description="Stable row identifier.")
    split: Optional[str] = Field(default=None, description="Public source split.")
    main_category: Optional[str] = Field(default=None, description="High-level political category.")
    topic_name: Optional[str] = Field(default=None, description="Political topic label.")
    partisan: Optional[str] = Field(default=None, description="Whether the source marks the topic partisan.")
    template_category: Optional[str] = Field(default=None, description="Prompt task category.")
    template: Optional[str] = Field(default=None, description="Prompt template before stance interpolation.")
    stance_a: Optional[str] = Field(default=None, description="First political stance.")
    stance_b: Optional[str] = Field(default=None, description="Opposing political stance.")
    prompt_a: Optional[str] = Field(default=None, description="First prompt generated by the paired agent.")
    prompt_b: Optional[str] = Field(default=None, description="Opposing prompt generated independently.")
    prompt_a_group: Optional[str] = Field(default=None, description="Interest group represented by prompt A.")
    prompt_b_group: Optional[str] = Field(default=None, description="Interest group represented by prompt B.")
    source_revision: Optional[str] = Field(default=None, description="Pinned source repository revision.")
    source_sha256: Optional[str] = Field(default=None, description="SHA-256 of the source CSV.")
    prompt_config: Optional[dict[str, object]] = Field(
        default=None,
        description="Null because rows already carry complete Responses API input.",
    )
