ether0:
  resources_servers:
    ether0:
      entrypoint: app.py
      domain: knowledge
      verified: false
      description: ether0 chemistry benchmark verifiers
      value: Evalutate chemistry knowledge and reasoning with ether0 benchmark
