code_gen:
  resources_servers:
    code_gen:
      entrypoint: app.py
      domain: coding
      verified: true
      verified_url: https://wandb.ai/nvidia/bxyu-nemo-gym-rl-integration-20250926/runs/54uzarwq
      description: Model must submit the right code to solve a problem
      value: Improve competitive coding capabilities
      num_processes: 8
      unit_test_timeout_secs: 10
      debug: false
