# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import base64
import json
import re
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from nemo_gym.openai_utils import (
    NeMoGymResponse,
    NeMoGymResponseCreateParamsNonStreaming,
    NeMoGymResponseOutputMessage,
    NeMoGymResponseOutputText,
)
from nemo_gym.server_utils import ServerClient
from resources_servers.leancat.app import (
    STATUS_BANNED_TOKENS,
    STATUS_COMPILE_ERROR,
    STATUS_COMPLETED,
    STATUS_EMPTY_GENERATION,
    STATUS_SANDBOX_ERROR,
    STATUS_STATEMENT_MODIFIED,
    STATUS_TIMEOUT,
    LeanCatResourcesServer,
    LeanCatResourcesServerConfig,
    LeanCatVerifyRequest,
)
from resources_servers.leancat.proof_utils import check_statement_preserved
from resources_servers.leancat.sandbox_client import GymSandboxLean4Client, Lean4SandboxClient


DATA_DIR = Path(__file__).absolute().parent.parent / "data"
PROMPTS_DIR = Path(__file__).absolute().parent.parent / "prompts"

REFERENCE = """import Mathlib

open CategoryTheory

variable {C : Type*} [Category.{v} C]

theorem id_comm (α β : (𝟭 C) ⟶ (𝟭 C)) : α ≫ β = β ≫ α := by
  sorry"""

SOLVED = """import Mathlib

open CategoryTheory

variable {C : Type*} [Category.{v} C]

theorem id_comm (α β : (𝟭 C) ⟶ (𝟭 C)) : α ≫ β = β ≫ α := by
  ext X
  exact (α.naturality (β.app X)).symm"""


def _load_rows(filename: str) -> list:
    return [json.loads(line) for line in (DATA_DIR / filename).read_text(encoding="utf-8").splitlines() if line]


# train.jsonl is gitignored and regenerated by prepare_leancat.py, so the full-dataset tests
# skip rather than fail on a fresh checkout. example.jsonl is committed and always runs.
needs_full_dataset = pytest.mark.skipif(
    not (DATA_DIR / "train.jsonl").exists(),
    reason="run prepare_leancat.py to generate data/train.jsonl",
)
needs_paper_d1_dataset = pytest.mark.skipif(
    not (DATA_DIR / "paper_d1_train.jsonl").exists(),
    reason="run prepare_leancat.py --prompt-variant paper-d1 to generate data/paper_d1_train.jsonl",
)

# (dataset file, template file) for each shipped prompt variant. Both are rendered from the
# same 100 problems; only the template differs.
PROMPT_VARIANTS = [
    ("example.jsonl", "static-passk.md"),
    ("paper_d1_example.jsonl", "paper-d1.md"),
]


class TestLeanCatApp:
    @pytest.fixture
    def config(self) -> LeanCatResourcesServerConfig:
        return LeanCatResourcesServerConfig(
            host="0.0.0.0",
            port=8080,
            entrypoint="",
            name="leancat",
            sandbox_host="127.0.0.1",
            sandbox_port=6000,
            compilation_timeout=300.0,
        )

    @pytest.fixture
    def server(self, config) -> LeanCatResourcesServer:
        return LeanCatResourcesServer(config=config, server_client=MagicMock(spec=ServerClient))

    def _create_response(self, text: str, msg_id: str = "test_msg") -> NeMoGymResponse:
        return NeMoGymResponse(
            id="test_response_id",
            created_at=1234567890.0,
            model="test_model",
            object="response",
            output=[
                NeMoGymResponseOutputMessage(
                    id=msg_id,
                    role="assistant",
                    type="message",
                    content=[
                        NeMoGymResponseOutputText(
                            type="output_text",
                            text=text,
                            annotations=[],
                        )
                    ],
                )
            ],
            parallel_tool_calls=False,
            tool_choice="none",
            tools=[],
        )

    def _create_request(
        self,
        text: str,
        formal_statement: str = REFERENCE,
        level: str = "Easy",
    ) -> LeanCatVerifyRequest:
        return LeanCatVerifyRequest(
            responses_create_params=NeMoGymResponseCreateParamsNonStreaming(input=[]),
            response=self._create_response(text),
            formal_statement=formal_statement,
            problem_id="0001",
            level=level,
            tag=["Basic"],
            domain=["Category"],
        )

    def _stub_sandbox(self, server: LeanCatResourcesServer, **output) -> AsyncMock:
        result = {"process_status": "completed", "stdout": "", "stderr": ""} | output
        mock = AsyncMock(return_value=result)
        server._sandbox_client.execute_lean4 = mock
        return mock

    @pytest.mark.asyncio
    async def test_verify_successful_proof(self, server):
        self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"Here you go.\n```lean4\n{SOLVED}\n```"))
        assert result.reward == 1.0
        assert result.proof_status == STATUS_COMPLETED
        assert result.statement_preserved
        assert result.failure_reason is None
        assert result.predicted_proof == SOLVED

    @pytest.mark.asyncio
    async def test_verify_row_metadata_survives_onto_the_response(self, server):
        # compute_subset_metrics groups on `level`, so it has to make it through verify.
        self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```", level="High"))
        assert result.level == "High"
        assert result.problem_id == "0001"

    @pytest.mark.asyncio
    async def test_verify_failed_proof(self, server):
        self._stub_sandbox(server, stderr="/lean4/my_project/x.lean:7:2: error: unknown tactic")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_COMPILE_ERROR
        assert result.compiler_output.stderr.endswith("unknown tactic")

    @pytest.mark.asyncio
    async def test_verify_zero_exit_with_sorry_warning(self, server):
        # `lake env lean` exits 0 on a sorry-carrying build; the status alone would pass it.
        self._stub_sandbox(server, stdout="warning: declaration uses 'sorry'")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_COMPILE_ERROR

    @pytest.mark.asyncio
    async def test_verify_timeout(self, server):
        self._stub_sandbox(server, process_status="timeout")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_TIMEOUT

    @pytest.mark.asyncio
    async def test_verify_sandbox_failure(self, server):
        self._stub_sandbox(server, process_status="error", stderr="connection refused")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_SANDBOX_ERROR

    @pytest.mark.asyncio
    async def test_verify_empty_generation(self, server):
        mock = self._stub_sandbox(server)
        result = await server.verify(self._create_request(""))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_EMPTY_GENERATION
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_rejects_sorry_without_compiling(self, server):
        mock = self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"```lean4\n{REFERENCE}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_BANNED_TOKENS
        assert "sorry" in result.failure_reason
        # A five-minute Mathlib compile must not be spent on a submission already lost.
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_rejects_weakened_statement_without_compiling(self, server):
        mock = self._stub_sandbox(server)
        cheat = SOLVED.replace("α ≫ β = β ≫ α", "True")
        result = await server.verify(self._create_request(f"```lean4\n{cheat}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_STATEMENT_MODIFIED
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_statement_guard_can_be_disabled(self, server):
        server.config.require_statement_preserved = False
        self._stub_sandbox(server)
        cheat = SOLVED.replace("α ≫ β = β ≫ α", "True")
        result = await server.verify(self._create_request(f"```lean4\n{cheat}\n```"))
        assert result.reward == 1.0
        # The guard still reports what it saw, so the run stays diagnosable.
        assert result.statement_preserved is False

    @pytest.mark.asyncio
    async def test_verify_compiles_the_whole_submitted_file(self, server):
        # The model owns the file here, unlike math_formal_lean: nothing is prepended.
        captured = {}

        async def capture_code(code: str, timeout: float):
            captured["code"] = code
            return {"process_status": "completed", "stdout": "", "stderr": ""}

        server._sandbox_client.execute_lean4 = capture_code
        await server.verify(self._create_request(f"Reasoning...\n```lean4\n{SOLVED}\n```"))
        assert captured["code"] == SOLVED


class TestMetrics:
    @pytest.fixture
    def server(self) -> LeanCatResourcesServer:
        config = LeanCatResourcesServerConfig(
            host="0.0.0.0",
            port=8080,
            entrypoint="",
            name="leancat",
            sandbox_host="127.0.0.1",
            sandbox_port=6000,
            compilation_timeout=300.0,
        )
        return LeanCatResourcesServer(config=config, server_client=MagicMock(spec=ServerClient))

    def _task(self, rewards, level):
        return [{"reward": r, "level": level, "statement_preserved": True} for r in rewards]

    def test_pass_at_k_is_broken_out_by_difficulty(self, server):
        tasks = [
            self._task([1.0, 0.0], "Easy"),
            self._task([0.0, 0.0], "Easy"),
            self._task([0.0, 0.0], "High"),
        ]
        metrics = server.compute_metrics(tasks)

        assert metrics["pass@1/accuracy"] == pytest.approx(100.0 * (0.5 + 0.0 + 0.0) / 3)
        assert metrics["pass@2/accuracy"] == pytest.approx(100.0 / 3)
        assert metrics["Easy/pass@2/accuracy"] == pytest.approx(50.0)
        assert metrics["High/pass@2/accuracy"] == pytest.approx(0.0)

    def test_statement_preserved_is_tracked_as_a_second_score(self, server):
        tasks = [[{"reward": 0.0, "level": "Easy", "statement_preserved": False}]]
        metrics = server.compute_metrics(tasks)
        assert metrics["pass@1/statement_preserved"] == pytest.approx(0.0)

    def test_no_tasks(self, server):
        assert server.compute_metrics([]) == {}

    def test_key_metrics_pick_the_highest_k(self, server):
        agent_metrics = {
            "mean/output_tokens": 12345.0,
            "pass@1/accuracy": 8.25,
            "pass@4/accuracy": 12.0,
            "pass@1[avg-of-4]/accuracy": 8.25,
        }
        key = server.get_key_metrics(agent_metrics)
        assert key["pass@4/accuracy"] == 12.0
        assert key["pass@1[avg-of-4]/accuracy"] == 8.25
        assert key["mean/output_tokens"] == 12345.0
        assert "pass@1/accuracy" not in key


class TestDataset:
    @pytest.mark.parametrize(
        "filename,expected_rows",
        [pytest.param("train.jsonl", 100, marks=needs_full_dataset), ("example.jsonl", 5)],
    )
    def test_rows_load_as_verify_requests(self, filename, expected_rows):
        rows = _load_rows(filename)
        assert len(rows) == expected_rows

        for row in rows:
            request = LeanCatVerifyRequest(
                responses_create_params=row["responses_create_params"],
                response=TestLeanCatApp()._create_response(""),
                **row["verifier_metadata"],
            )
            assert request.formal_statement
            assert request.level in {"Easy", "Medium", "High"}
            # Every task is a hole to fill; a row with no `sorry` would be unsolvable by
            # construction, since filling nothing still leaves the file unchanged.
            assert "sorry" in request.formal_statement

    @needs_full_dataset
    def test_guard_accepts_every_reference_statement_with_its_holes_filled(self):
        """The statement guard must not reject an honest answer on any of the 100 tasks.

        A false positive here is invisible in a real run -- it just looks like the model
        failed -- so it is checked against every shipped row rather than a sample. The
        substitution stands in for the minimal honest submission: the reference file with
        each hole replaced by a tactic and nothing else touched.
        """
        rejected = []
        for row in _load_rows("train.jsonl"):
            statement = row["verifier_metadata"]["formal_statement"]
            filled = re.sub(r"\bsorry\b", "aesop_cat", statement)
            preserved, reason = check_statement_preserved(statement, filled)
            if not preserved:
                rejected.append((row["verifier_metadata"]["problem_id"], reason))
        assert rejected == []

    def test_prompt_contains_the_statement(self):
        for row in _load_rows("example.jsonl"):
            prompt = row["responses_create_params"]["input"][0]["content"]
            assert row["verifier_metadata"]["formal_statement"] in prompt

    @pytest.mark.parametrize("dataset,template", PROMPT_VARIANTS)
    def test_prompt_is_rendered_exactly_as_upstream_renders_it(self, dataset, template):
        """Lock the prompt to upstream's ``template.format(formal_statement=...)``.

        The offline half of the fidelity check: it pins the committed template and the
        rendering, so a change to either shows up as a test failure rather than as a
        benchmark number that quietly stops being comparable to the paper's. The half that
        needs the network -- that our formal_statement is the ``CAT_statement/*.lean`` bytes
        verbatim, trailing newline included -- is enforced in prepare_leancat.py, which
        fails if the .lean file and the JSONL record disagree.
        """
        rendered = (PROMPTS_DIR / template).read_text(encoding="utf-8").strip()
        for row in _load_rows(dataset):
            expected = rendered.format(formal_statement=row["verifier_metadata"]["formal_statement"])
            assert row["responses_create_params"]["input"][0]["content"] == expected

    @pytest.mark.parametrize("filename", ["example.jsonl", "paper_d1_example.jsonl"])
    def test_rows_carry_a_single_user_message(self, filename):
        # Upstream's chat_completion posts exactly [{"role": "user", ...}] with no system
        # prompt; a system message here would make our numbers incomparable to the paper's.
        for row in _load_rows(filename):
            messages = row["responses_create_params"]["input"]
            assert [m["role"] for m in messages] == ["user"]


class TestPromptVariants:
    """The two shipped templates must stay distinct, and both must stay renderable.

    The repo template is byte-exact against upstream; the paper one is a transcription of a
    typeset listing, so it cannot be. These tests pin what *is* checkable: that the pair has
    not silently collapsed into one, and that both still carry the placeholder.
    """

    def test_both_templates_carry_the_placeholder(self):
        for _, template in PROMPT_VARIANTS:
            assert "{formal_statement}" in (PROMPTS_DIR / template).read_text(encoding="utf-8")

    def test_the_two_templates_really_differ(self):
        repo = (PROMPTS_DIR / "static-passk.md").read_text(encoding="utf-8")
        paper = (PROMPTS_DIR / "paper-d1.md").read_text(encoding="utf-8")
        assert repo != paper
        # The substantive divergence: the repo permits auxiliary declarations and names the
        # banned tokens; the paper asks for step-by-step reasoning instead.
        assert "auxiliary definitions" in repo and "auxiliary definitions" not in paper
        assert "step by step" in paper and "step by step" not in repo

    def test_upstream_template_is_unmodified(self):
        """prepare_leancat.py must never write a --prompt file over the pinned upstream copy."""
        import hashlib

        digest = hashlib.sha256((PROMPTS_DIR / "static-passk.md").read_bytes()).hexdigest()
        assert digest.startswith("7948825d3c4373b6")

    @needs_paper_d1_dataset
    def test_variants_cover_the_same_problems(self):
        repo_ids = [r["verifier_metadata"]["problem_id"] for r in _load_rows("train.jsonl")]
        paper_ids = [r["verifier_metadata"]["problem_id"] for r in _load_rows("paper_d1_train.jsonl")]
        assert repo_ids == paper_ids
        assert len(repo_ids) == 100

    @needs_paper_d1_dataset
    def test_variants_differ_only_in_the_prompt(self):
        for a, b in zip(_load_rows("train.jsonl"), _load_rows("paper_d1_train.jsonl")):
            assert a["verifier_metadata"] == b["verifier_metadata"]
            assert a["responses_create_params"] != b["responses_create_params"]


class TestGymSandboxBackend:
    """Selecting and driving `nemo_gym.sandbox` instead of the HTTP sandbox server."""

    def _config(self, **overrides) -> LeanCatResourcesServerConfig:
        base = dict(host="0.0.0.0", port=8080, entrypoint="", name="leancat", compilation_timeout=300.0)
        return LeanCatResourcesServerConfig(**{**base, **overrides})

    def _server(self, config) -> LeanCatResourcesServer:
        return LeanCatResourcesServer(config=config, server_client=MagicMock(spec=ServerClient))

    def test_http_client_is_the_default(self):
        server = self._server(self._config())
        assert isinstance(server._sandbox_client, Lean4SandboxClient)

    def test_sandbox_provider_selects_the_gym_backend(self):
        server = self._server(
            self._config(
                sandbox_provider={"enroot": {}},
                sandbox_spec={"image": "base.sqsh"},
                lean_project_dir="/lean4/my_project",
            )
        )
        assert isinstance(server._sandbox_client, GymSandboxLean4Client)
        assert server._sandbox_client.lean_project_dir == "/lean4/my_project"

    def test_unknown_sandbox_spec_key_fails_loudly(self):
        client = GymSandboxLean4Client(provider={"enroot": {}}, spec={"image": "x.sqsh", "bogus": 1})
        with pytest.raises(ValueError, match="Unknown sandbox_spec keys: bogus"):
            client._build_spec()

    @pytest.mark.asyncio
    async def test_exec_ships_the_file_as_base64_and_runs_lake_env_lean(self):
        captured = {}

        class _Result:
            stdout, stderr, return_code, error_type = "", "", 0, None

        class _Sandbox:
            async def exec(self, command, timeout_s=None):
                captured["command"] = command
                return _Result()

        client = GymSandboxLean4Client(provider={"enroot": {}}, spec={}, lean_project_dir="/lean4/proj")
        client._sandbox = _Sandbox()

        # Quotes, backslashes and unicode are all routine in Lean; none may reach the shell.
        code = 'theorem t : True := by\n  have h : "a\\"b" = "a\\"b" := rfl\n  trivial  -- 𝟭 ≫ α'
        result = await client.execute_lean4(code, timeout=42.0)

        assert result["process_status"] == "completed"
        assert result["return_code"] == 0
        command = captured["command"]
        assert "lake env lean" in command and "cd /lean4/proj" in command
        # The source must appear only as base64, never inline.
        assert base64.b64encode(code.encode()).decode() in command
        assert "theorem t" not in command
        # A failed compile must not be masked by the cleanup's exit status.
        assert "status=$?" in command and "exit $status" in command

    @pytest.mark.asyncio
    async def test_nonzero_exit_scores_zero_even_with_no_error_text(self):
        """`lake env lean` can fail without the word "error:" in captured output.

        String-matching alone would call that a proof, so the exit status has to win.
        """
        server = self._server(self._config(sandbox_provider={"enroot": {}}, sandbox_spec={}))
        server._sandbox_client.execute_lean4 = AsyncMock(
            return_value={"process_status": "completed", "stdout": "", "stderr": "", "return_code": 1}
        )
        app = TestLeanCatApp()
        result = await server.verify(app._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_COMPILE_ERROR

    @pytest.mark.asyncio
    async def test_zero_exit_scores_one(self):
        server = self._server(self._config(sandbox_provider={"enroot": {}}, sandbox_spec={}))
        server._sandbox_client.execute_lean4 = AsyncMock(
            return_value={"process_status": "completed", "stdout": "", "stderr": "", "return_code": 0}
        )
        app = TestLeanCatApp()
        result = await server.verify(app._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 1.0
        assert result.proof_status == STATUS_COMPLETED

    @pytest.mark.asyncio
    async def test_sandbox_start_failure_is_a_diagnosable_zero_not_a_crash(self):
        client = GymSandboxLean4Client(provider={"nonexistent_provider": {}}, spec={})
        result = await client.execute_lean4("theorem t : True := trivial")
        assert result["process_status"] == "error"
        assert "Sandbox start failed" in result["stderr"]
