# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import re
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from nemo_gym.openai_utils import (
    NeMoGymResponse,
    NeMoGymResponseCreateParamsNonStreaming,
    NeMoGymResponseOutputMessage,
    NeMoGymResponseOutputText,
)
from nemo_gym.server_utils import ServerClient
from resources_servers.leancat.app import (
    STATUS_BANNED_TOKENS,
    STATUS_COMPILE_ERROR,
    STATUS_COMPLETED,
    STATUS_EMPTY_GENERATION,
    STATUS_SANDBOX_ERROR,
    STATUS_STATEMENT_MODIFIED,
    STATUS_TIMEOUT,
    LeanCatResourcesServer,
    LeanCatResourcesServerConfig,
    LeanCatVerifyRequest,
)
from resources_servers.leancat.proof_utils import check_statement_preserved


DATA_DIR = Path(__file__).absolute().parent.parent / "data"
PROMPTS_DIR = Path(__file__).absolute().parent.parent / "prompts"

REFERENCE = """import Mathlib

open CategoryTheory

variable {C : Type*} [Category.{v} C]

theorem id_comm (α β : (𝟭 C) ⟶ (𝟭 C)) : α ≫ β = β ≫ α := by
  sorry"""

SOLVED = """import Mathlib

open CategoryTheory

variable {C : Type*} [Category.{v} C]

theorem id_comm (α β : (𝟭 C) ⟶ (𝟭 C)) : α ≫ β = β ≫ α := by
  ext X
  exact (α.naturality (β.app X)).symm"""


def _load_rows(filename: str) -> list:
    return [json.loads(line) for line in (DATA_DIR / filename).read_text(encoding="utf-8").splitlines() if line]


# train.jsonl is gitignored and regenerated by prepare_leancat.py, so the full-dataset tests
# skip rather than fail on a fresh checkout. example.jsonl is committed and always runs.
needs_full_dataset = pytest.mark.skipif(
    not (DATA_DIR / "train.jsonl").exists(),
    reason="run prepare_leancat.py to generate data/train.jsonl",
)


class TestLeanCatApp:
    @pytest.fixture
    def config(self) -> LeanCatResourcesServerConfig:
        return LeanCatResourcesServerConfig(
            host="0.0.0.0",
            port=8080,
            entrypoint="",
            name="leancat",
            sandbox_host="127.0.0.1",
            sandbox_port=6000,
            compilation_timeout=300.0,
        )

    @pytest.fixture
    def server(self, config) -> LeanCatResourcesServer:
        return LeanCatResourcesServer(config=config, server_client=MagicMock(spec=ServerClient))

    def _create_response(self, text: str, msg_id: str = "test_msg") -> NeMoGymResponse:
        return NeMoGymResponse(
            id="test_response_id",
            created_at=1234567890.0,
            model="test_model",
            object="response",
            output=[
                NeMoGymResponseOutputMessage(
                    id=msg_id,
                    role="assistant",
                    type="message",
                    content=[
                        NeMoGymResponseOutputText(
                            type="output_text",
                            text=text,
                            annotations=[],
                        )
                    ],
                )
            ],
            parallel_tool_calls=False,
            tool_choice="none",
            tools=[],
        )

    def _create_request(
        self,
        text: str,
        formal_statement: str = REFERENCE,
        level: str = "Easy",
    ) -> LeanCatVerifyRequest:
        return LeanCatVerifyRequest(
            responses_create_params=NeMoGymResponseCreateParamsNonStreaming(input=[]),
            response=self._create_response(text),
            formal_statement=formal_statement,
            problem_id="0001",
            level=level,
            tag=["Basic"],
            domain=["Category"],
        )

    def _stub_sandbox(self, server: LeanCatResourcesServer, **output) -> AsyncMock:
        result = {"process_status": "completed", "stdout": "", "stderr": ""} | output
        mock = AsyncMock(return_value=result)
        server._sandbox_client.execute_lean4 = mock
        return mock

    @pytest.mark.asyncio
    async def test_verify_successful_proof(self, server):
        self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"Here you go.\n```lean4\n{SOLVED}\n```"))
        assert result.reward == 1.0
        assert result.proof_status == STATUS_COMPLETED
        assert result.statement_preserved
        assert result.failure_reason is None
        assert result.predicted_proof == SOLVED

    @pytest.mark.asyncio
    async def test_verify_row_metadata_survives_onto_the_response(self, server):
        # compute_subset_metrics groups on `level`, so it has to make it through verify.
        self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```", level="High"))
        assert result.level == "High"
        assert result.problem_id == "0001"

    @pytest.mark.asyncio
    async def test_verify_failed_proof(self, server):
        self._stub_sandbox(server, stderr="/lean4/my_project/x.lean:7:2: error: unknown tactic")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_COMPILE_ERROR
        assert result.compiler_output.stderr.endswith("unknown tactic")

    @pytest.mark.asyncio
    async def test_verify_zero_exit_with_sorry_warning(self, server):
        # `lake env lean` exits 0 on a sorry-carrying build; the status alone would pass it.
        self._stub_sandbox(server, stdout="warning: declaration uses 'sorry'")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_COMPILE_ERROR

    @pytest.mark.asyncio
    async def test_verify_timeout(self, server):
        self._stub_sandbox(server, process_status="timeout")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_TIMEOUT

    @pytest.mark.asyncio
    async def test_verify_sandbox_failure(self, server):
        self._stub_sandbox(server, process_status="error", stderr="connection refused")
        result = await server.verify(self._create_request(f"```lean4\n{SOLVED}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_SANDBOX_ERROR

    @pytest.mark.asyncio
    async def test_verify_empty_generation(self, server):
        mock = self._stub_sandbox(server)
        result = await server.verify(self._create_request(""))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_EMPTY_GENERATION
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_rejects_sorry_without_compiling(self, server):
        mock = self._stub_sandbox(server)
        result = await server.verify(self._create_request(f"```lean4\n{REFERENCE}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_BANNED_TOKENS
        assert "sorry" in result.failure_reason
        # A five-minute Mathlib compile must not be spent on a submission already lost.
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_rejects_weakened_statement_without_compiling(self, server):
        mock = self._stub_sandbox(server)
        cheat = SOLVED.replace("α ≫ β = β ≫ α", "True")
        result = await server.verify(self._create_request(f"```lean4\n{cheat}\n```"))
        assert result.reward == 0.0
        assert result.proof_status == STATUS_STATEMENT_MODIFIED
        mock.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_verify_statement_guard_can_be_disabled(self, server):
        server.config.require_statement_preserved = False
        self._stub_sandbox(server)
        cheat = SOLVED.replace("α ≫ β = β ≫ α", "True")
        result = await server.verify(self._create_request(f"```lean4\n{cheat}\n```"))
        assert result.reward == 1.0
        # The guard still reports what it saw, so the run stays diagnosable.
        assert result.statement_preserved is False

    @pytest.mark.asyncio
    async def test_verify_compiles_the_whole_submitted_file(self, server):
        # The model owns the file here, unlike math_formal_lean: nothing is prepended.
        captured = {}

        async def capture_code(code: str, timeout: float):
            captured["code"] = code
            return {"process_status": "completed", "stdout": "", "stderr": ""}

        server._sandbox_client.execute_lean4 = capture_code
        await server.verify(self._create_request(f"Reasoning...\n```lean4\n{SOLVED}\n```"))
        assert captured["code"] == SOLVED


class TestMetrics:
    @pytest.fixture
    def server(self) -> LeanCatResourcesServer:
        config = LeanCatResourcesServerConfig(
            host="0.0.0.0",
            port=8080,
            entrypoint="",
            name="leancat",
            sandbox_host="127.0.0.1",
            sandbox_port=6000,
            compilation_timeout=300.0,
        )
        return LeanCatResourcesServer(config=config, server_client=MagicMock(spec=ServerClient))

    def _task(self, rewards, level):
        return [{"reward": r, "level": level, "statement_preserved": True} for r in rewards]

    def test_pass_at_k_is_broken_out_by_difficulty(self, server):
        tasks = [
            self._task([1.0, 0.0], "Easy"),
            self._task([0.0, 0.0], "Easy"),
            self._task([0.0, 0.0], "High"),
        ]
        metrics = server.compute_metrics(tasks)

        assert metrics["pass@1/accuracy"] == pytest.approx(100.0 * (0.5 + 0.0 + 0.0) / 3)
        assert metrics["pass@2/accuracy"] == pytest.approx(100.0 / 3)
        assert metrics["Easy/pass@2/accuracy"] == pytest.approx(50.0)
        assert metrics["High/pass@2/accuracy"] == pytest.approx(0.0)

    def test_statement_preserved_is_tracked_as_a_second_score(self, server):
        tasks = [[{"reward": 0.0, "level": "Easy", "statement_preserved": False}]]
        metrics = server.compute_metrics(tasks)
        assert metrics["pass@1/statement_preserved"] == pytest.approx(0.0)

    def test_no_tasks(self, server):
        assert server.compute_metrics([]) == {}

    def test_key_metrics_pick_the_highest_k(self, server):
        agent_metrics = {
            "mean/output_tokens": 12345.0,
            "pass@1/accuracy": 8.25,
            "pass@4/accuracy": 12.0,
            "pass@1[avg-of-4]/accuracy": 8.25,
        }
        key = server.get_key_metrics(agent_metrics)
        assert key["pass@4/accuracy"] == 12.0
        assert key["pass@1[avg-of-4]/accuracy"] == 8.25
        assert key["mean/output_tokens"] == 12345.0
        assert "pass@1/accuracy" not in key


class TestDataset:
    @pytest.mark.parametrize(
        "filename,expected_rows",
        [pytest.param("train.jsonl", 100, marks=needs_full_dataset), ("example.jsonl", 5)],
    )
    def test_rows_load_as_verify_requests(self, filename, expected_rows):
        rows = _load_rows(filename)
        assert len(rows) == expected_rows

        for row in rows:
            request = LeanCatVerifyRequest(
                responses_create_params=row["responses_create_params"],
                response=TestLeanCatApp()._create_response(""),
                **row["verifier_metadata"],
            )
            assert request.formal_statement
            assert request.level in {"Easy", "Medium", "High"}
            # Every task is a hole to fill; a row with no `sorry` would be unsolvable by
            # construction, since filling nothing still leaves the file unchanged.
            assert "sorry" in request.formal_statement

    @needs_full_dataset
    def test_guard_accepts_every_reference_statement_with_its_holes_filled(self):
        """The statement guard must not reject an honest answer on any of the 100 tasks.

        A false positive here is invisible in a real run -- it just looks like the model
        failed -- so it is checked against every shipped row rather than a sample. The
        substitution stands in for the minimal honest submission: the reference file with
        each hole replaced by a tactic and nothing else touched.
        """
        rejected = []
        for row in _load_rows("train.jsonl"):
            statement = row["verifier_metadata"]["formal_statement"]
            filled = re.sub(r"\bsorry\b", "aesop_cat", statement)
            preserved, reason = check_statement_preserved(statement, filled)
            if not preserved:
                rejected.append((row["verifier_metadata"]["problem_id"], reason))
        assert rejected == []

    def test_prompt_contains_the_statement(self):
        for row in _load_rows("example.jsonl"):
            prompt = row["responses_create_params"]["input"][0]["content"]
            assert row["verifier_metadata"]["formal_statement"] in prompt

    @pytest.mark.parametrize("filename", [pytest.param("train.jsonl", marks=needs_full_dataset), "example.jsonl"])
    def test_prompt_is_rendered_exactly_as_upstream_renders_it(self, filename):
        """Lock the prompt to upstream's ``template.format(formal_statement=...)``.

        The offline half of the fidelity check: it pins the committed template and the
        rendering, so a change to either shows up as a test failure rather than as a
        benchmark number that quietly stops being comparable to the paper's. The half that
        needs the network -- that our formal_statement is the ``CAT_statement/*.lean`` bytes
        verbatim, trailing newline included -- is enforced in prepare_leancat.py, which
        fails if the .lean file and the JSONL record disagree.
        """
        template = (PROMPTS_DIR / "static-passk.md").read_text(encoding="utf-8").strip()
        for row in _load_rows(filename):
            expected = template.format(formal_statement=row["verifier_metadata"]["formal_statement"])
            assert row["responses_create_params"]["input"][0]["content"] == expected

    @pytest.mark.parametrize("filename", [pytest.param("train.jsonl", marks=needs_full_dataset), "example.jsonl"])
    def test_rows_carry_a_single_user_message(self, filename):
        # Upstream's chat_completion posts exactly [{"role": "user", ...}] with no system
        # prompt; a system message here would make our numbers incomparable to the paper's.
        for row in _load_rows(filename):
            messages = row["responses_create_params"]["input"]
            assert [m["role"] for m in messages] == ["user"]
