# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the small documentation index, not a runtime environment registry."""

import argparse
import json
import re
import tomllib
from pathlib import Path


def table_cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "&#124;")


def render_index(root: Path) -> str:
    recipes = json.loads((root / "fern/onboarding-recipes.json").read_text(encoding="utf-8"))
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    seen = set()
    for recipe in recipes:
        page = recipe["page"]
        if not re.fullmatch(r"get-started/[a-z0-9-]+\.mdx", page):
            raise ValueError(f"Invalid recipe page: {page}")
        if not (root / "fern/versions/latest/pages" / page).is_file():
            raise ValueError(f"Missing recipe page: {page}")
        if page in seen:
            raise ValueError(f"Duplicate recipe page: {page}")
        seen.add(page)
    lines = [
        "---",
        'title: "Benchmark onboarding recipes"',
        'description: "Benchmark contribution guides and small runnable examples."',
        "position: 4",
        "---",
        "",
        "# Benchmark onboarding recipes",
        "",
        "{/* Generated by scripts/generate_onboarding_index.py; recipe metadata: fern/onboarding-recipes.json. */}",
        "",
        "## Contribution Guides",
        "",
        "Choose a review destination:",
        "",
        "- [Public GitHub PR to main](/main/contribute/environments/benchmark-public-contribution).",
        "- [Private GitLab MR to nv-internal-main](/main/contribute/environments/benchmark-private-contribution).",
        "",
        "Both guides use the same [authoring and review checklist](/main/contribute/environments/benchmark-contribution).",
        "",
        "## Optional Examples",
        "",
        "Use these small examples to check setup before adapting a benchmark. This index is not a hosted registry;",
        "see each recipe for its validation limits. Start with [Onboarding Setup](/main/get-started/onboarding-setup).",
        "",
        f"The checkout requires Python `{project['project']['requires-python']}`. Adapter pins below are read from",
        "the checked-in requirements. Follow each recipe's Python and server setup instructions,",
        "and record `git rev-parse HEAD` with your results.",
        "",
        "| Recipe | Adapter revision | Prerequisites | Review route |",
        "| --- | --- | --- | --- |",
    ]
    for recipe in recipes:
        revision = "Native Gym scaffold (this checkout)"
        if dependency_file := recipe.get("dependency_file"):
            requirements = (root / dependency_file).read_text(encoding="utf-8").splitlines()
            matches = [line for line in requirements if line.startswith(recipe["dependency_name"] + " @ ")]
            pin = matches[0].rsplit("@", 1)[-1] if len(matches) == 1 else ""
            if not re.fullmatch(r"[a-f0-9]{40}|v?\d+\.\d+\.\d+(?:[-+][\w.-]+)?", pin):
                raise ValueError(f"Expected an exact commit or version pin in {dependency_file}")
            revision = f"`{pin}`"
        route = "/main/" + recipe["page"].removesuffix(".mdx")
        lines.append(
            f"| [{table_cell(recipe['title'])}]({route}) | {revision} | "
            f"{table_cell(recipe['prerequisites'])} | {table_cell(recipe['review_route'])} |"
        )
    lines += [
        "",
        "## Validation scope",
        "",
        "Read these dimensions independently. A fixture pass is not a real-model rollout, a parity study,",
        "or proof of complete traces. The adapters remain experimental until their declared acceptance checks pass.",
        "",
        "| Recipe | Structural | Runtime | Parity | Trace |",
        "| --- | --- | --- | --- | --- |",
    ]
    for recipe in recipes:
        cells = (table_cell(recipe[key]) for key in ("title", "structural", "runtime", "parity", "trace"))
        lines.append("| " + " | ".join(cells) + " |")
    lines += [
        "",
        "For a new benchmark, preserve dataset/split, prompt, agent, model, image, resource, timeout and verifier",
        "identity. Keep raw artifacts and separately report execution failures, valid zero scores and missing evidence.",
        "See [benchmark contribution guidance](/main/contribute/environments/adding-a-benchmark) and",
        "[rollout health](/main/evaluation/rollout-health). Health checks report evidence; they do not certify completion.",
        "",
        "## Keep the index current",
        "",
        "After changing a recipe, its validation evidence, or an adapter pin, run from the checkout root:",
        "",
        "```bash",
        "python scripts/generate_onboarding_index.py",
        "python scripts/generate_onboarding_index.py --check",
        "```",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="Fail on stale output without changing files")
    args = parser.parse_args(argv)
    output = args.root / "fern/versions/latest/pages/get-started/benchmark-onboarding.mdx"
    try:
        rendered = render_index(args.root)
    except (OSError, ValueError, KeyError) as error:
        print(f"Cannot generate onboarding index: {error}")
        return 2
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            print("Onboarding index is stale. Run python scripts/generate_onboarding_index.py")
            return 1
        print("Onboarding index is current.")
        return 0
    output.write_text(rendered, encoding="utf-8")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
