terminus_judge_resources_server:
  resources_servers:
    terminus_judge:
      entrypoint: app.py
      judge_model_server:
        type: responses_api_models
        name: policy_model
      judge_responses_create_params:
        input: []
        max_output_tokens: 1024
      judge_prompt_template_fpath: prompt_templates/terminus_prompt.txt
      judge_endpoint_max_concurrency: null
      judge_system_message: null
      judge_equal_label: '[[A=B]]'
      judge_not_equal_label: '[[A!=B]]'
      check_twice_swap: true
      reward_if_swap_fails: 0.0
      enable_string_similarity: true
      string_similarity_threshold: 0.9
      enable_llm_judge: true
      domain: agent
      verified: false
      description: single-step terminal based task (simple judge prompt)
      value: Improve on terminal-style tasks
