apiVersion: v1
kind: Service
metadata:
  name: gym-head-svc
  namespace: gym
  labels:
    app.kubernetes.io/name: gym-head
    app.kubernetes.io/part-of: nemo-gym
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gym-head
  ports:
    - port: 11000
      targetPort: http
      protocol: TCP
      name: http
