mini_swe_agent_resources_server:
  resources_servers:
    mini_swe_agent:
      entrypoint: app.py
      domain: coding
      verified: false
      description: A software development with mini-swe-agent orchestration
      value: Improve software development capabilities, like SWE-bench
